version: '3'

services:
  postgres:
    image: "postgres:12.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: unfurls
      POSTGRES_DB: spaceSlackUnfurls
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d spaceSlackUnfurls -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
